// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// flash
void flash(const NumericMatrix& Y, NumericMatrix& expA, NumericMatrix& expB, NumericMatrix& expA2, NumericMatrix& expB2, NumericMatrix& piMat, NumericMatrix& phiMat, NumericVector& sig2Vec);
RcppExport SEXP vifa_flash(SEXP YSEXP, SEXP expASEXP, SEXP expBSEXP, SEXP expA2SEXP, SEXP expB2SEXP, SEXP piMatSEXP, SEXP phiMatSEXP, SEXP sig2VecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type expA(expASEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type expB(expBSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type expA2(expA2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type expB2(expB2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type piMat(piMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type phiMat(phiMatSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type sig2Vec(sig2VecSEXP);
    flash(Y, expA, expB, expA2, expB2, piMat, phiMat, sig2Vec);
    return R_NilValue;
END_RCPP
}
