# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' EM Algorithm for FLASH.
#'
#' @param Y The data matrix.
#' @param expA A matrix whose \eqn{(i, l)}th entry is the initial value for the variational mean
#'     of \eqn{a_{il}}.
#' @param expB A matrix whose \eqn{(j, l)}th entry is the initial value for the variational mean
#'     of \eqn{b_{jl}}.
#' @param expA2 A matrix whose \eqn{(i, l)}th entry is the initial value for the variational mean
#'     of \eqn{a_{il}^2}.
#' @param expB2 A matrix whose \eqn{(j, l)}th entry is the initial value for the variational mean
#'     of \eqn{b_{jl}^2}.
#' @param piMat The initial values of the mixing proportions of the A's. The rows index the
#'     factors and the columns index the mixing distributions. Thus, \code{piMat.nrow()}
#'     should equal \code{expA.ncol()}.
#' @param phiMat The initial values of hte mixing proportions of the B's. The rows index
#'     the factors and the columns index the mixing distribution. Thus, \code{phiMat.nrow()}
#'     should equal \code{expB.ncol()}.
#' @param sig2Vec A vector of the initial values of the column-specific variances.
#'
#' @author David Gerard
#'
flash <- function(Y, expA, expB, expA2, expB2, piMat, phiMat, sig2Vec) {
    invisible(.Call('vifa_flash', PACKAGE = 'vifa', Y, expA, expB, expA2, expB2, piMat, phiMat, sig2Vec))
}

